#!/usr/bin/env node
const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');

// Run from project root
const rootDir = path.resolve(__dirname, '../..');
const configPath = path.join(rootDir, 'packages', 'all-tests', 'vitest.config.ts');
const reportsDir = path.join(__dirname, 'reports');
const templatePath = path.join(__dirname, 'template.html');

// Ensure reports directory exists
if (!fs.existsSync(reportsDir)) {
  fs.mkdirSync(reportsDir, { recursive: true });
}

// Use vitest from root node_modules
const vitestCmd = process.platform === 'win32' ? 'vitest.CMD' : 'vitest';
const vitestBin = path.join(rootDir, 'node_modules', '.bin', vitestCmd);

const vitest = spawn(vitestBin, ['--watch', '--coverage', '--config', configPath], {
  cwd: rootDir,
  shell: true,
  stdio: ['inherit', 'pipe', 'pipe'],
});

let fileCount = 0;
let testCount = 0;
let coveragePercent = null;
let coverageDetails = null;
let summaryShown = false;
let windowTimeout = null;
let buffer = '';
let testFiles = [];
let allTests = [];

vitest.stdout.on('data', (data) => {
  buffer += data.toString();
  process.stdout.write(data);
  checkAndShowSummary();
});

vitest.stderr.on('data', (data) => {
  buffer += data.toString();
  process.stderr.write(data);
  checkAndShowSummary();
});

function checkAndShowSummary() {
  // Remove ANSI escape codes
  const cleanBuffer = buffer.replace(/\x1b\[[0-9;]*m/g, '');

  // Parse test results from "Test Files" line
  const testFilesMatch = cleanBuffer.match(/Test Files\s+(\d+) passed/);
  const testsMatch = cleanBuffer.match(/Tests\s+(\d+) passed/);

  if (testFilesMatch) {
    fileCount = parseInt(testFilesMatch[1]);
  }
  if (testsMatch) {
    testCount = parseInt(testsMatch[1]);
  }

  // Parse coverage percentage from "All files" line
  const coverageMatch = buffer.match(/All files\s+\|\s*([\d.]+)/);
  if (coverageMatch) {
    coveragePercent = parseFloat(coverageMatch[1]).toFixed(1);
  }

  // Parse duration
  const durationMatch = cleanBuffer.match(/Duration\s+(.+?)\s/);
  const duration = durationMatch ? durationMatch[1].trim() : 'N/A';

  // Parse test files, all tests and coverage details
  parseTestFiles(cleanBuffer);
  parseAllTests();
  parseCoverageDetails(cleanBuffer);

  // Show summary at the very end
  if (cleanBuffer.includes('Waiting for file changes') && fileCount > 0 && !summaryShown) {
    if (!windowTimeout) {
      windowTimeout = setTimeout(() => {
        summaryShown = true;

        // Generate HTML report
        generateHtmlReport(duration);

        console.log('\n╔════════════════════════════════════════════════════════════════╗');
        console.log('║                       📊 ALL TESTS SUMMARY                        ║');
        console.log('╠══════════════════════════════════════════════════════════════════╣');
        console.log(`║  📁 Test Files:   ${String(fileCount).padStart(3)} passed (${fileCount} total)                   ║`);
        console.log(`║  ✅ Tests:        ${String(testCount).padStart(3)} passed (${testCount} total)                   ║`);
        if (coveragePercent !== null && parseFloat(coveragePercent) > 0) {
          console.log(`║  📊 Coverage:     ${String(coveragePercent + '%').padStart(6)}                                          ║`);
        }
        console.log('╚════════════════════════════════════════════════════════════════╝\n');

        // Reset for next run
        setTimeout(() => {
          fileCount = 0;
          testCount = 0;
          coveragePercent = null;
          coverageDetails = null;
          summaryShown = false;
          buffer = '';
          windowTimeout = null;
          testFiles = [];
          allTests = [];
        }, 500);
      }, 100);
    }
  }

  // Keep buffer from growing too large
  if (buffer.length > 15000) {
    buffer = buffer.slice(-10000);
  }
}

function parseTestFiles(cleanBuffer) {
  // Parse individual test files from output
  // Format: "✓ all-tests ../path/to/test.ts (16 tests) 10ms"
  const testPattern = /\s+✓\s+all-tests\s+(.+?)\s+\((\d+) test[s]?\)/g;
  const matches = [...cleanBuffer.matchAll(testPattern)];

  testFiles = matches.map(m => ({
    name: m[1],
    count: parseInt(m[2])
  }));
}

function parseAllTests() {
  // Parse all individual tests from JSON file generated by vitest
  allTests = [];

  const jsonPath = path.join(reportsDir, 'test-results.json');
  if (!fs.existsSync(jsonPath)) {
    return;
  }

  try {
    const jsonContent = fs.readFileSync(jsonPath, 'utf8');
    const jsonResult = JSON.parse(jsonContent);

    if (jsonResult.testResults) {
      for (const testFile of jsonResult.testResults) {
        const filePath = testFile.name;
        // Vitest uses 'assertionResults' not 'tests'
        const tests = testFile.assertionResults || [];
        for (const test of tests) {
          // Use 'title' for the test name and 'fullName' for full path
          allTests.push({
            file: filePath,
            name: test.title || test.fullName || 'unknown test',
            fullName: test.fullName || test.name,
            status: test.status || 'passed'
          });
        }
      }
    }
  } catch (e) {
    // JSON not ready or invalid, skip
    console.error('Error parsing test results:', e.message);
  }
}

function parseCoverageDetails(cleanBuffer) {
  // Parse detailed coverage table
  const lines = cleanBuffer.split('\n');
  const coverageTable = [];
  let inCoverageTable = false;

  for (const line of lines) {
    if (line.includes('Coverage report from')) {
      inCoverageTable = true;
      continue;
    }
    if (inCoverageTable && line.includes('----------')) {
      continue;
    }
    if (inCoverageTable && line.trim() === '') {
      break;
    }
    if (inCoverageTable) {
      const parts = line.split('|').map(p => p.trim()).filter(p => p && p !== 'File');
      if (parts.length >= 5) {
        const name = parts[0];
        if (name !== 'All files' && !name.includes('...')) {
          coverageTable.push({
            file: name,
            stmts: parts[1],
            branch: parts[2],
            funcs: parts[3],
            lines: parts[4]
          });
        }
      }
    }
  }

  coverageDetails = coverageTable;
}

function generateHtmlReport(duration) {
  const formattedTime = new Date().toLocaleString();

  // Helper function to make path relative to project root
  function makeRelativePath(filePath) {
    // Convert absolute path to relative path
    if (path.isAbsolute(filePath)) {
      const relative = path.relative(rootDir, filePath);
      return relative.split(path.sep).join('/');
    }
    return filePath;
  }

  // Helper function to get color class based on percentage
  function getColorClass(value) {
    const percent = parseFloat(value) || 0;
    if (percent >= 80) return 'cell-high';
    if (percent >= 50) return 'cell-medium';
    if (percent > 0) return 'cell-low';
    return 'cell-empty';
  }

  // Helper function to get test status icon and class
  function getTestStatusIcon(status) {
    switch (status) {
      case 'passed': return '<span class="test-status passed">✓</span>';
      case 'failed': return '<span class="test-status failed">✗</span>';
      case 'skipped': return '<span class="test-status skipped">⊘</span>';
      case 'todo': return '<span class="test-status todo">○</span>';
      default: return '<span class="test-status passed">✓</span>';
    }
  }

  // Parse coverage details HTML - compact table rows
  let coverageTableRows = '';
  if (coverageDetails && coverageDetails.length > 0) {
    for (const item of coverageDetails) {
      const relativePath = makeRelativePath(item.file);
      coverageTableRows += `
        <tr>
          <td class="file-cell" title="${relativePath}">${relativePath}</td>
          <td class="metric-cell ${getColorClass(item.stmts)}">${item.stmts}</td>
          <td class="metric-cell ${getColorClass(item.branch)}">${item.branch}</td>
          <td class="metric-cell ${getColorClass(item.funcs)}">${item.funcs}</td>
          <td class="metric-cell ${getColorClass(item.lines)}">${item.lines}</td>
        </tr>
      `;
    }
  }

  // Parse all tests HTML - collapsible file groups
  let testsHtml = '';
  if (allTests.length > 0) {
    // Group by file
    const testsByFile = {};
    for (const test of allTests) {
      const relativePath = makeRelativePath(test.file);
      if (!testsByFile[relativePath]) {
        testsByFile[relativePath] = [];
      }
      testsByFile[relativePath].push(test);
    }

    for (const [file, tests] of Object.entries(testsByFile)) {
      testsHtml += `
        <div class="test-file">
          <div class="test-file-header" onclick="toggleTests(this)">
            <div class="test-file-name">${file}</div>
            <div class="test-count-badge">${tests.length} tests</div>
            <span class="toggle-icon">▼</span>
          </div>
          <div class="test-list">
      `;

      for (const test of tests) {
        testsHtml += `
              <div class="test-case">${getTestStatusIcon(test.status)}${test.name}</div>
        `;
      }

      testsHtml += `
          </div>
        </div>
      `;
    }
  }

  // Count files
  const coverageFileCount = coverageDetails ? coverageDetails.length : 0;
  const testFileCount = testFiles ? testFiles.length : 0;

  // Read template and replace placeholders
  let html = fs.readFileSync(templatePath, 'utf8');
  html = html.replace(/{{timestamp}}/g, formattedTime);
  html = html.replace(/{{fileCount}}/g, fileCount);
  html = html.replace(/{{testCount}}/g, testCount);
  html = html.replace(/{{coveragePercent}}/g, coveragePercent || '0');
  html = html.replace(/{{duration}}/g, duration);
  html = html.replace(/{{coverageTableRows}}/g, coverageTableRows || '<tr><td colspan="5" class="cell-empty">No coverage data available</td></tr>');
  html = html.replace(/{{coverageFileCount}}/g, coverageFileCount);
  html = html.replace(/{{testsList}}/g, testsHtml || '<p>No test data available</p>');
  html = html.replace(/{{testFileCount}}/g, testFileCount);

  // Save HTML report
  const reportPath = path.join(reportsDir, `report-${Date.now()}.html`);
  fs.writeFileSync(reportPath, html);

  // Clean up old reports (keep only 10)
  cleanupOldReports();

  // Log report location
  console.log(`\n📄 HTML Report saved: ${reportPath}`);
}

function cleanupOldReports() {
  const files = fs.readdirSync(reportsDir)
    .filter(f => f.startsWith('report-') && f.endsWith('.html'))
    .map(f => ({
      name: f,
      path: path.join(reportsDir, f),
      time: parseInt(f.match(/report-(\d+)\.html/)?.[1] || '0')
    }))
    .sort((a, b) => b.time - a.time);

  // Keep only 10 most recent
  if (files.length > 10) {
    const toDelete = files.slice(10);
    for (const file of toDelete) {
      fs.unlinkSync(file.path);
    }
  }
}
